config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  

  concern :commentable do

    resources :comments

  end
  
  resources :quests, concerns: :commentable, shallow: true do
      resources :answers, concerns: :commentable
  end
  
  root 'quests#index'
end

app/models/quest.rb
class Quest < ApplicationRecord
  include PgSearch
 
  after_save :reindex

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable
  has_many :comments, as: :commentable
  belongs_to :user
  accepts_nested_attributes_for :attachments
  accepts_nested_attributes_for :comments
  has_many :subscriptions, foreign_key: :post_id, dependent: :destroy
  has_many :users, through: :subscriptions, dependent: :destroy
  
  multisearchable against: [:title, :body]

  validates :title, :body, presence: true
  validates_length_of :title, :within => 3..250
  validates_length_of :body, :within => 3..2000

  #after_create :send_author

  private

  def reindex
    PgSearch::Multisearch.rebuild(Quest)
  end
end

app/controllers/api/v1/quests_controller.rb
class Api::V1::QuestsController < Api::V1::BaseController
  skip_before_action :verify_authenticity_token, :only => [:create]
  before_action :load_quest, only: :show

  def index
    @quests = Quest.all
    respond_with(@quests, each_serializer: ListQuestSerializer)
  end

  def show
    respond_with(@quest, serializer: QuestSerializer)
  end

  def create
    @quest = Quest.new(quest_params.merge(user: current_resource_owner))
    if @quest.save
      respond_with @quest
    else
      #render @quest.errors.messages.to_json
    end

  end
 
  protected

  def load_quest
    @quest = Quest.find(params[:id])
  end

  def quest_params
    params.require(:quest).permit(:title, :body, :user, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
 before_action :authenticate_user!,  only: [:new, :create, :edit, :update, :destroy]
 before_action :load_quest, only: [:show, :edit, :update, :destroy]

 before_action :build_answer, only: :show
 
 respond_to :js, only: :update
 
 def index
   respond_with(@quests=Quest.all)
 end
 
 def show
  respond_with @quest
 end
 
 def new
   respond_with(@quest = Quest.new)

 end
 
 def create
   @quest = Quest.new(quest_params.merge(user: current_user))

   @quest.save 
   respond_with @quest

 end
 
  def edit
  end
  
  def update
    @quest.update(quest_params)

    respond_with @quest  

  end

  def destroy
    respond_with(@quest.destroy)
  end
 
  private

  def load_quest
    @quest = Quest.find(params[:id])
  end
  

  def build_answer
    @answer=@quest.answers.build
  end
  

  def quest_params
  	params.require(:quest).permit(:title, :body, :user, attachments_attributes: [:id, :file, :_destroy])
  end
  
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_answers.html.slim
-@quest.answers.any?
- @quest.answers.each do |answer|
  -if answer.persisted?
    .answer id="answer-#{answer.id}"

      p= answer.body
      p Comments:
      .answer-comments
        = render 'comments/list', parent: answer
      
    p Attachments:
    ul
      -answer.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url

        
      -if user_signed_in? && current_user == answer.user
        p= link_to 'Edit', '', class: 'edit-answer-link', data: {answer_id: answer.id}
        p
          = form_for answer, remote: true, json: {id: "edit-answer-#{answer.id}"}, data: { type: :json } do |f|
            = f.label :body, 'Answer'
            .answer-errors
            = f.text_area :body
            = f.submit 'Save'

        p= link_to 'Удалить ответ',  answer, method: :delete, data: { confirm: 'Вы уверены?' } 

        
      h4 Attachments:
      ul
        -answer.attachments.each do |a|
          li= link_to a.file.identifier, a.file.url
      h4 Comments:
      .answer-comments
        = render 'comments/list', parent: answer  
      

app/views/quests/_quest.html.slim
 p= @quest.title
 p= @quest.body
 p Comments:
 .comments
   = render 'comments/list', parent: @quest
 p Attachments:
 ul
   -@quest.attachments.each do |a|
     li= link_to a.file.identifier, a.file.url

 
  -if user_signed_in? && current_user == @quest.user
    p= link_to 'Edit','', class: 'edit-quest-link', data: {quest_id: @quest.id}
    p
      = form_for [@quest], remote: true, html: {id: "edit_quest_#{@quest.id}"} do |f|
        = f.label :title
        .quest-errors
        = f.text_field :title, id: :quest_title
        = f.label :body
        = f.text_field :body, id: :quest_body
        = f.submit 'Save'
    p= link_to 'Удалить вопрос', @quest, method: :delete, data: { confirm: 'Вы уверены?' }
  h4 Attachments:
  ul
    -@quest.attachments.each do |a|
      li= link_to a.file.identifier, a.file.url
  h4 Comments:
  .quest-comments
    = render 'comments/list', parent: @quest

app/views/quests/_quests.html.slim
-@quests=Quest.all
-if @quests.any?
  - @quests.each do |quest|
    .quest id="quest-#{quest.id}"
    h3= link_to quest.title, quest
    h4= quest.body

    h4 Attachments:
    -if quest.attachments.any?
      ul
      -quest.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
    h4 Answer:
    -if quest.answers.any?
      ul
      -quest.answers.each do |a|
        li=a.body
    -if policy(quest).update?

      p= link_to 'Edit', edit_quest_path(quest) if can?(:update, quest)
    -if policy(quest).destroy?

      p= link_to 'Удалить вопрос', quest, method: :delete, data: { confirm: 'Вы уверены?' }  if can?(:delate, quest)
      
    

app/views/quests/create.js.erb
 <% if @comment.errors.present? %>
   <% @comment.errors.full_messages.each do |message| %>
      $('.comment-errors').html('<%= j message %>');
   <% end %>
    
   <% else %> 
    <% publish_to "/quests" do %>
       $('.quests').html('<%= j render 'quests' %>');
     <% end %>
     $('.new_quest #quest_title').val('');
     $('.new_quest #quest_body').val('');
     
 <% end %>
 
 

app/views/quests/edit.html.slim
h1 Редактировать вопрос
- if @quest.errors.any?
    div id="error_explanation"
      h2= pluralize(@quest.errors.count, "error prohibited this quest from being saved:") 
      
      ul
      -@quest.errors.full_messages.each do |message| 
         li= message

= form_for @quest, remote: true do |f| 
  
  = f.label :title 
  = f.text_field :title, id: :quest_title
  = f.label :body
  = f.text_field :body, id: :quest_body

  = f.submit 'Изменить'

= link_to 'Назад', quests_path

app/views/quests/index.html.slim
<h1>Список записей </h1>

.quests 
  = render 'quests'
  .quest-errors  
-if user_signed_in?
  h4 New question:
  = form_for @quest, remote: true do |f|
    p       
      = f.label :title
      = f.text_field :title
    p
      = f.label :body
      = f.text_area :body
    p Attachments:

    ul
     -q.attachments.each do |a|
       li= link_to a.file.identifier, a.file.url
         
    -if current_user == q.user
      p= link_to 'Изменить вопрос', quest_path(q)
      p= link_to 'Удалить', q, method: :delete, data: { confirm: 'Вы уверены?' }

    
     

app/views/quests/new.html.slim
= form_for @quest, remote: true do |f|
  
  p       
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments, @quest.attachments.build do |a|
      = a.label :file
      = a.file_field :file
      
  = f.submit 'Create'
= subscribe_to "/quests"
p  
  = link_to 'Назад', quests_path

app/views/quests/show.html.slim
<h1> Question </h1>
 = link_to 'Назад', quests_path
.quest  
  = render 'quest'
  .quest-errors
  
     
.answers data={quest_id: "#{@quest.id}"}
  = render 'answers'

-if user_signed_in?  
  = form_for [@quest, @answer], remote: true do |f|
    = f.label :body, 'You answer'
    .answer-errors
    = f.text_area :body
    p Attachments:
    p 
      = f.fields_for :attachments, @answer.attachments.build, remote: true, class: 'attachments', data: { type: :json } do |a|
        = a.label :file
        = a.file_field :file
    = f.submit 'Create'

= subscribe_to "/quests/#{@quest.id}/answers"

 

app/views/quests/update.js.erb
 <% if @quest.errors.present? %>
   <% @quest.errors.full_messages.each do |message| %>
      $('.quest-errors').html('<%= j message %>');
   <% end %>  
 <% else %>
   $('.quest').html('<%= j render 'quests/quest' %>');
   $('.edit-quest-link').click(function (e) {
       e.preventDefault();
       $(this).hide();
       quest_id = $(this).data('questId');
       $('form#edit-quest-'+ quest_id).show();
   });
   
 
   $('.quests').html('<%= j render 'quests/quests' %>');
   $('.edit-answer-link').click(function (e) {
       e.preventDefault();
       $(this).hide();
       quest_id = $(this).data('questId');
       $('form#edit-quest-'+ quest_id).show();
   });
 <% end %>
   